# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"metric-adapter"},"name":"metric-adapter","namespace":"crane-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"metric-adapter"}},"template":{"metadata":{"labels":{"app":"metric-adapter"},"name":"metric-adapter"},"spec":{"containers":[{"args":["/metric-adapter","--secure-port=6443","--alsologtostderr=true"],"image":"docker.io/gocrane/metric-adapter:v0.2.0","imagePullPolicy":"IfNotPresent","name":"metric-adapter","ports":[{"containerPort":6443,"name":"https"},{"containerPort":8080,"name":"http"}],"volumeMounts":[{"mountPath":"/tmp","name":"temp-vol"}]}],"serviceAccountName":"metric-adapter","volumes":[{"emptyDir":{},"name":"temp-vol"}]}}}}
    meta.helm.sh/release-name: crane
    meta.helm.sh/release-namespace: crane-system
  creationTimestamp: "2022-04-07T03:25:20Z"
  generation: 2
  labels:
    app: metric-adapter
    app.kubernetes.io/instance: crane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crane
    app.kubernetes.io/version: v0.3.0
    helm.sh/chart: crane-0.3.0
  name: metric-adapter
  namespace: crane-system
  resourceVersion: "4854"
  uid: 6502b218-765c-4da1-9429-13e125e20ea7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metric-adapter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metric-adapter
      name: metric-adapter
    spec:
      containers:
        - args:
            - /metric-adapter
            - --secure-port=6443
            - --alsologtostderr=true
          command:
            - /metric-adapter
          image: docker.io/gocrane/metric-adapter:v0.2.0
          imagePullPolicy: IfNotPresent
          name: metric-adapter
          ports:
            - containerPort: 6443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: readyz
              port: 6443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metric-adapter
      serviceAccountName: metric-adapter
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: temp-vol
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-04-07T03:25:30Z"
      lastUpdateTime: "2022-04-07T03:25:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-04-07T03:25:20Z"
      lastUpdateTime: "2022-04-07T03:26:18Z"
      message: ReplicaSet "metric-adapter-7d9964b9df" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
