apiVersion: apps/v1
kind: Deployment       #API 对象类型
metadata:
  name: dex            #Deployment name
spec:
  replicas: 1          #副本数量
  selector:
    matchLabels:
      app: dex
  template:            #副本模版
    metadata:
      labels:
        app: dex
    spec:
      containers:
        - name: dex
          image: 871779972/dex:v1.0     #镜像名
          ports:
            - containerPort: 8082                      #容器端口，与DockerFile 暴露出来的端口保持一致
---
apiVersion: v1
kind: Service
metadata:
  name: dex-svc            #自定义的服务名
spec:
  type: NodePort           #
  ports:
    - port: 80        #服务监听的端口
      targetPort: 8082       #转发到后端的端口号
      protocol: TCP
      name: http
  selector:
    app: dex               #Deployment name