apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-test
  name: service-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-test
  template:
    metadata:
      labels:
        app: service-test
    spec:
      containers:
        - image: docker.io/871779972/service-test:v0.2
          name: service-test
          ports:
            - containerPort: 80
              name: service-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-test
  name: service-test
spec:
  type: ClusterIP
  ports:
    - name: "service-test"
      port: 80
      targetPort: 80
  selector:
    app: service-test
