apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: docker.io/871779972/test:v0.3
          name: backend
          ports:
            - containerPort: 8080
              name: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: "backend-service"
      port: 8080
      targetPort: 8080
  selector:
    app: backend
