apiVersion: v1
kind: Pod
metadata:
  name: "{{.AppName}}"
  namespace: {{.Namespace}}
  annotations:
    yunhang-platform/tool: backup
spec:
  containers:
    - name:  "{{.AppName}}"
      image: "{{.ImageName}}" #镜像名固定
      args: {{.Args}}
#        - devops
#        - save
#        - --in-mongo-endpoint="{{.InMongoEndpoint}}"
#        - --in-mysql-endpoint="{{.InMysqlEndpoint}}"
#        - --in-minio-endpoint="{{.InMinioEndpoint}}"
#        - --in-minio-bucket="{{.InMinioBucket}}bucket"
#        - --out-minio-endpoint="{{.OutMinioEndpoint}}"
#        - --out-minio-bucket="{{.OutMinioBucket}}"
#        - --out-minio-file="{{.OutMinioFile}}"
#        - --out-sftp-endpoint="{{.OutSftpEndpoint}}"
#        - --out-sftp-file="{{.OutSftpFile}}"
#        - --out-volume-file="{{.OutVolumeFile}}"
      volumeMounts:
        - mountPath: /backup/kubernetes/out/minio/
          name: minio-secret
        - mountPath: /backup/kubernetes/in/minio/
          name: devops-minio-secret
        - mountPath: /backup/kubernetes/out/sftp/
          name: sftp-secret
  volumes:
    - name: minio-secret
      configMap:
        name: minio-creds-config
    - name: devops-minio-secret
      configMap:
        name: devops-minio-creds-config
    - name: sftp-secret
      configMap:
        name: sftp-creds-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-creds-config
  namespace: {{.Namespace}}
data:
  accessKey: AKIAIOSFODNN72019EXAMPLE
  secretKey: wJalrXUtnFEMI2019K7MDENGbPxRfiCYEXAMPLEKEY

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-minio-creds-config
  namespace: {{.Namespace}}
data:
  accessKey: AKIAIOSFODNN72019EXAMPLE
  secretKey: wJalrXUtnFEMI2019K7MDENGbPxRfiCYEXAMPLEKEY


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-creds-config
  namespace: {{.Namespace}}
data:
  username: root
  password: yunhang
