apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapdemo
  namespace: ssodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldapdemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ldapdemo
    spec:
      containers:
        - env:
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_ADMIN_PASSWORD
              value: adminpassword
            - name: LDAP_ROOT
              value: dc=demo,dc=cn
          image: bitnami/openldap:latest
          imagePullPolicy: Always
          name: openldap
          ports:
            - containerPort: 1389
              name: service
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ldapdemo
  namespace: ssodemo
spec:
  type: NodePort
  ports:
    - port: 1389
      protocol: TCP
      targetPort: 1389
      name: http
  selector:
    app: ldapdemo
