# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: crane
    meta.helm.sh/release-namespace: crane-system
  labels:
    app: crane-agent
    app.kubernetes.io/instance: crane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crane
    app.kubernetes.io/version: v0.3.0
    helm.sh/chart: crane-0.3.0
  name: crane-agent
  namespace: crane-system
  resourceVersion: "4463"
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: health-metric-port
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: crane-agent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
