# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"craned","namespace":"crane-system"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":9443}],"selector":{"app":"craned"}}}
    meta.helm.sh/release-name: crane
    meta.helm.sh/release-namespace: crane-system
  creationTimestamp: "2022-04-07T03:25:20Z"
  labels:
    app.kubernetes.io/instance: crane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crane
    app.kubernetes.io/version: v0.3.0
    helm.sh/chart: crane-0.3.0
  name: craned
  namespace: crane-system
  resourceVersion: "5097"
  uid: db4dc377-b166-4c93-a633-9f061e8bc4f0
spec:
  clusterIP: 10.96.99.90
  clusterIPs:
    - 10.96.99.90
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: craned
      nodePort: 31376
      port: 443
      protocol: TCP
      targetPort: 9443
    - name: crane-server
      nodePort: 31131
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: dashboard-service
      nodePort: 30828
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: craned
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
      - hostname: localhost
