# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  name: craned
  namespace: crane-system
  resourceVersion: "5097"
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: craned
      nodePort: 31376
      port: 443
      protocol: TCP
      targetPort: 9443
    - name: crane-server
      nodePort: 31131
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: dashboard-service
      nodePort: 30828
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: craned
  sessionAffinity: None
  type: NodePort
