# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: crane-system
  creationTimestamp: "2022-04-07T03:23:42Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.8.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: crane-system
  resourceVersion: "4005"
  uid: 1426a52f-7fef-4d10-b6bd-924712b0c122
spec:
  clusterIP: 10.110.63.219
  clusterIPs:
    - 10.110.63.219
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
