apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          name: service1
          image: 10.0.5.73:5000/agent/agent:v1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: service-data
              mountPath: /data
      volumes:
        - name: service-data
          persistentVolumeClaim:
            claimName: service-data
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
