apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: crane
  namespace: crane-system
spec:
  components:
    - name: crane
      type: helm
      properties:
        repoType: git
        url: https://github.com/gocrane/crane
        chart: ./charts/crane/v0.3.0
        git:
          branch: master
        values:
          featureGates: PreDownloadImageForInPlaceUpdate=true
      timeout:
        install: 10m
  workflow:
    steps:
      - name: apply-resources
        type: apply-application