apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-test
  name: client-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-test
  template:
    metadata:
      labels:
        app: client-test
    spec:
      containers:
        - image: docker.io/871779972/client-test:v0.6
          name: client-test
          ports:
            - containerPort: 8081
              name: client-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-test
  name: client-test
spec:
  type: NodePort
  ports:
    - name: "client-test"
      port: 8081
      targetPort: 8081
  selector:
    app: client-test
