apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          name: service2
          image: 10.0.5.73:5000/agent/agent:v2.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: service-data
              mountPath: /data
      volumes:
        - name: service-data
          persistentVolumeClaim:
            claimName: service-data
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

