# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.crane-system.svc.cluster.local:8080
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
    mkdir -p /var/lib/grafana/dashboards/default
  grafana.ini: "[analytics]\ncheck_for_updates = true\n[auth.anonymous]\nenabled =
    true\norg_name = Main Org.\norg_role = Viewer\n[auth.proxy]\nauto_sign_up = true\nenable_login_token
    = false\nenabled = false\nheader_name = X-WEBAUTH-USER\nheader_property = username\nheaders
    = \nsync_ttl = 60\nwhitelist = \n[grafana_net]\nurl = https://grafana.net\n[log]\nmode
    = console\n[paths]\ndata = /var/lib/grafana/\nlogs = /var/log/grafana\nplugins
    = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n[security]\nallow_embedding
    = true\n[server]\nroot_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.4.2
    helm.sh/chart: grafana-6.25.1
  name: grafana
  namespace: crane-system
  resourceVersion: "736"

