# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIyMDQxMTA2MzMxOVoXDTMyMDQwODA2MzMxOVowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANMB
    Duv311hNpdUCqF3ury/bHlCMprhOcnZq43mfd7FqjQIgS1OdznmYqBXlYAbdNneH
    xoMmgZyT/4hxZhU4XLVAMPuF2psG3S6khnHuCawYboG0iLRFHYki9SISJvuC1o+R
    kLdif+L3epB8MmV9M4xg2jrnynCxwfxpcBBygvP64IBtYg+ew7+T0Pa9DAMOYp5+
    Vl5BnOTQC4KMSfpnuZkbubtutAVUhlWZIUvn4B/KT0zVB297VFyzV8+47MtWhXeR
    BRyCHFuBwwNZWBnK1sFIOqP6QoDEiTa+L8xQMXWYjavJNQM/mi5WwSaJ83JNLdZe
    zUR9IxfS0BqDqHTh3EMCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFOp1kZpMHUAVNP6IRF6Jci9OIhG8MBUGA1UdEQQO
    MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAAlJqwK73YhlEwf5B60H
    R1WbK3eT0QVQpswxYz1siNVg2vtWaxr5na3ciW3zsXaog3A8YGPhyzT2Ew82M/C8
    xBBHRlrQR4BKFtjGWnT1kG1X8eaQeBBuh5DbhKFkijDjsOH1/qGyFFglONd7GOUs
    2HX7YBN4fm+VGTf8VgJpBWAN1R9n6DC+49W8mRJArbaYEjbP0VjC18r/bl0BPdio
    Dnek/a20sRX9hL6dcOVITnAibJoww/is8wG23AxV72kd9SU3nAJTdDE3yry6Yn2U
    GUUQcK34djwvE04njE2RIUJpW7nvKUYpoev2Rf5PXb4nlGc57WyR2plQUwzaaZGt
    ShM=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: crane-system
  resourceVersion: "608"
  uid: 65080b08-1483-4ffa-9bc1-a79a89a8d061
