# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  config_set.yaml: |-
    apiVersion: analysis.crane.io/v1alpha1
    kind: ConfigSet
    configs:
      - targets: []
        properties:
          resource.cpu-request-percentile: "0.98"
          ehpa.deployment-min-replicas: "1"
          ehpa.statefulset-min-replicas: "1"
          ehpa.workload-min-replicas: "1"
          ehpa.pod-min-ready-seconds: "30"
          ehpa.pod-available-ratio: "0.5"
          ehpa.default-min-replicas: "2"
          ehpa.max-replicas-factor: "3"
          ehpa.min-cpu-usage-threshold: "10"
          ehpa.fluctuation-threshold: "1.5"
          ehpa.min-cpu-target-utilization: "30"
          ehpa.max-cpu-target-utilization: "75"
          ehpa.reference-hpa: "true"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: crane
    meta.helm.sh/release-namespace: crane-system
  labels:
    app.kubernetes.io/instance: crane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crane
    app.kubernetes.io/version: v0.3.0
    helm.sh/chart: crane-0.3.0
  name: recommendation-config
  namespace: crane-system
  resourceVersion: "836"
